services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:${DB_PORT}"
  neo4j:
    image: neo4j:latest
    volumes:
      - ./neo4j/logs:/logs
      - ./neo4j/config:/config
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
    ports:
      - "7474:${NEO4J_FRONT}"
      - "7687:${NEO4J_PORT}"
    restart: always
  nlp:
    build:
      dockerfile: nlp_service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      NEO4J_HOST: ${NEO4J_HOST}
      NEO4J_PORT: ${NEO4J_PORT}
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
    volumes:
      - ./nlp_service:/opt/app
  assistant_service:
    build:
      dockerfile: assistant_service/Dockerfile
    ports:
      - "5001:${ASSISTANT_SERVICE_PORT}"
    environment:
      ASSISTANT_SERVICE_HOST: ${ASSISTANT_SERVICE_HOST}
      ASSISTANT_SERVICE_PORT: ${ASSISTANT_SERVICE_PORT}
      LLM_MODEL_PATH: ${LLM_MODEL_PATH}
      LLM_MODEL_FILE: ${LLM_MODEL_FILE}
  user_backend:
    build:
      dockerfile:  user_api.Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_SYNCHRONIZE: ${DB_SYNCHRONIZE}
      DB_TYPE: ${DB_TYPE}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}

    depends_on:
      - mysql