# Generated by Django 5.1.3 on 2024-11-23 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alive', models.BooleanField(default=True)),
                ('word', models.CharField(max_length=256)),
                ('lemma', models.CharField(max_length=256)),
                ('definition', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Word token',
                'verbose_name_plural': 'Word tokens',
                'unique_together': {('word', 'lemma')},
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alive', models.BooleanField(default=True)),
                ('user_id', models.CharField(max_length=1024)),
                ('word_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tokens', to='core.wordtoken')),
            ],
            options={
                'verbose_name': 'User token',
                'verbose_name_plural': 'User tokens',
            },
        ),
    ]
