# Generated by Django 5.1.3 on 2024-11-23 19:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pathology',
                'verbose_name_plural': 'Pathologies',
            },
        ),
    ]
