 version: '3'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"

#Conexion con chat
  chatbot:
    build: ./chatbot
    container_name: chatbot
    ports:
      - "3000:3000"
    depends_on:
      - neo4j
